### PR TITLE
feat(Checks): add Slack notifications

### PR DESCRIPTION
**Pull request by FanaHOVA**
Adding Slack notifications for checks. 

Setup:
- Get a Webhook URL from Slack and set it as an ENV variable
- When creating a check, specify your Slack channel
- Receive Slack notifications at the same pace as email notifications

### CODE REVIEW

**Comment by luddement** [comment]
Hello!

Not sure if the 'slack-notifier' gem is necessary. Maybe it is better to remove it and just do a plain request. Something like:

```
  def notify_slack(message, channel)
    slack_url = ENV['WEBHOOK_URL']
    return unless slack_url.present?

    params = {
      text: message,
      channel: channel
    }

    uri = URI.parse(slack_url)
    http = Net::HTTP.new(uri.host, uri.port)
    http.use_ssl = true

    request = Net::HTTP::Post.new(uri.request_uri)
    request.body = params.to_json
    http.request(request)
  end
```

**Comment by FanaHOVA** [comment]
@luddement yea I was thinking about that. I wanted to leave the notifier in because people might want to hack on it and build cooler stuff on top of it, but it's probably better to keep dependencies light since it might not be needed for most people. Give me a couple mins to fix it up!

**Comment by FanaHOVA** [comment]
@luddement realized that straight webhooks don't support changing channel for each notification, so I've swapped it to a checkbox. I guess most people will want notifications in the same channel, so it shouldn't be a big deal. If there's a request for it, we can allow that in the future.

CCing @blairanderson since he asked about this and obviously CCing @ankane for help in moving forward with this :)

**Comment by feliperaul** [comment]
This would be really nice !

**Comment by ankane** [comment]
Hey @FanaHOVA, big thanks for the PR 💯 and sorry it took so long to get to. This is great!

I think it's best to support multiple channels, so went that route. Added in https://github.com/ankane/blazer/commit/756d9156dd2e9bf870739a161a39d4e26fadcf75.

**Pull request closed without merging**
