### PR TITLE
Make things more mobile responsive

### PR DESCRIPTION
**Pull request by jules2689**
I noticed there were a few areas that weren't mobile responsive:
- Tables
- Top Bar

To accomodate this:
- Added `table-responsive` divs (bootstrap) around the tables
  - this wasn't enough for large tables in queries on large screens, so I also added a slight dashed board to the table outline and made it scroll to match the behaviour bootstrap does on mobile
- Added a `yield :topbar` which lets us get rid of the `position: fixed` and use dynamic height.
  - This is outside the container, so position fixed isn't necessary
  - I converted top navs over to this format.
- Changed some `float: right` styles to `pull-right` classes from bootstrap
- Moved `blazer/nav` to the right to make room for the title on mobile and to simple consolidate buttons

**All views should be roughly the same....**

| Before | After |
| --- | --- |
| image | image |

**Or better!**

| Before | After |
| --- | --- |
| image | image |
| image | image |
| image | image |

cc @ankane

### CODE REVIEW

**Comment by giedriusr** [comment]
looks awesome 👍

**Comment by jules2689** [comment]
ping @ankane

**Comment by ankane** [comment]
Hey @jules2689, thanks for the PR 👍  I'm happy to make Blazer more mobile friendly. A few comments:

- This changeset is really large, which makes it harder to review. I'd recommend breaking it into smaller pieces, and keeping it as small as possible. Maybe start a with a single view.
- I'd prefer tp keep the nav on the left.

**Comment by ankane** [comment]
Closing as there's been no discussion in months. Feel free to address the points above and submit a new PR.

**Comment by jules2689** [comment]
Argh. Sorry. I kept meaning to get back to this, but by the time I did there were a bunch of merge conflicts. I meant to close this sooner. Sorry.

**Pull request closed without merging**
