### PR TITLE
Use assets path from yml file

### PR DESCRIPTION
**Pull request by charusat09**

### CODE REVIEW

**Comment by ankane** [comment]
Hey @charusat09, what the use case for this?

**Comment by charusat09** [comment]
@ankane We have custom routes for assets. I was not able to use this gem since default `/assets` path is not accessible through our routes. So, I make it configurable so that, anyone with different settings for routes can use this gem. Thanks.

**Comment by ankane** [comment]
Unfortunately, I don't think this is common enough to include an option for.

**Comment by charusat09** [comment]
Ok. Make sense. Anyways, I have stared using my forked version.

**Pull request closed without merging**
