### PR TITLE
Add Public/Shareable queries

### PR DESCRIPTION
**Pull request by FanaHOVA**
Refers to issue https://github.com/ankane/blazer/issues/56

WIP PR. Missing:
- Allow multiple endpoints for export (JSON, CSV, etc)
- Don't allow Query edit while accessing a public page when not logged in OR when the user hasn't proved HTTP authentication details.

### CODE REVIEW

**Comment by ewalk153** [comment]
@FanaHOVA - I need this feature as well, would be happy to collaborate on it! I just pull down your branch. ideally, the `Blazer::ExportsController` would not redirect to the queries page, but instead just render the content from this controller.

In my case, I don't want to expose the private database `Query.id` attribute. Would you mind if I add a commit to your branch to experiment with this?

**Comment by FanaHOVA** [comment]
@ewalk153 That's totally fine! It's been a really packed month and work and got little time for OS :( I was thinking of using `SecureRandom.uuid` to expose a public ID for each query since it'd mean no additional dependencies. What do you think?

**Comment by ewalk153** [comment]
100% agree.

**Comment by ewalk153** [comment]
It's not pretty, but I think this works.

https://github.com/Flatbook/blazer/tree/ew/public-sharing.

Wanna give it a shot?

**Comment by FanaHOVA** [comment]
@ewalk153 like @xymbol was saying I think the `included` block isn't necessary. That's a hook called when you include the concern in the controller, so defining them in there doesn't really change much other than probably slowing it down a bit (I have no proof to back this up, just a gut feeling, callbacks/hooks always scare me :P). Other than that, looks good!

**Comment by ewalk153** [comment]
I just tested it. I narrowed the `included` block down to just wrapping the `helper_method :blazer_time_value` line.

**Comment by ewalk153** [comment]
Thanks @FanaHOVA and @xymbol for the feedback.

**Comment by FanaHOVA** [comment]
@ewalk153 great; shouldn't you point your PR to my branch so we can merge it together and then ask @ankane to review? 🙂

**Comment by ewalk153** [comment]
I'll make the PR!

**Comment by ewalk153** [comment]
PR made: https://github.com/FanaHOVA/blazer/pull/1

**Comment by FanaHOVA** [comment]
@ankane can you take a look at this? I merged @ewalk153's PR into mine, would be good to get some pointers from you with what changes are needed (if any)

**Pull request closed without merging**
