### PR TITLE
add bigquery adapter

### PR DESCRIPTION
**Pull request by pedrocarmona**
Hi @ankane,

Thank you very much for this gem.

In this PR is implemented the BigQuery adapter.

It includes:
- run_statement
- tables
- schema
- preview statement
- the instructions

### CODE REVIEW

**Comment by ankane** [comment]
Hey @pedrocarmona, this is great 👍  Adding a few comments inline.

**Comment by ankane** [comment]
Decided to try it out instead. Works really well, so going to merge. 💯 

I'll make it so the `url` setting isn't required.

**Comment by ankane** [comment]
Did some cleanup to match the style of the project: https://github.com/ankane/blazer/commit/325207c9439c4f20a0b5e075cb218cbb857dfaf8.

One notable change is that the global log level change was removed, as it can be unexpected/undesired for devs.

**Comment by pedrocarmona** [comment]
Thanks @ankane :)

**Pull request merged**
