### PR TITLE
Allow non-ASCII filename

### PR DESCRIPTION
**Pull request by aki77**
Allowing non-ASCII filename.

### CODE REVIEW

**Comment by ankane** [comment]
Hey @aki77, thanks for the PR 👍  Can you share an example that doesn't currently work that this PR fixes? I'm unable to reproduce.

**Comment by aki77** [comment]
When the query name is `テスト`.

Expected behavior: `テスト.csv`
Observed behavior: `query.csv`

**Comment by ankane** [comment]
Hey @aki77, sorry for the delay. Not sure I understand all the logic. It looks like a similar result can be achieved with:

```
original_name = @query.try(:name)
name = original_name.try(:parameterize).presence
name ||= original_name ? URI.encode(original_name) : "query"
```

What am I missing?

**Comment by ankane** [comment]
Cleaning up stale PRs. See my last comment if you're still interested in continuing the discussion.

**Comment by aki77** [comment]
Sorry for replying late!
When using the parameterize method, multibyte characters are deleted.

```
irb(main):001:0> 'test'.try(:parameterize)
=> "test"
irb(main):002:0> 'テスト'.try(:parameterize)
=> ""
```

**Comment by ankane** [comment]
The code above address that.

**Comment by aki77** [comment]
I misread the code.

When the query name is `テスト1`.
Expected behavior: `テスト1`
Actual behavior: `1`

**Comment by aki77** [comment]
I referenced to the `carrierwave` code.
https://github.com/carrierwaveuploader/carrierwave/blob/master/lib/carrierwave/sanitized_file.rb#L324-L331

**Pull request closed without merging**
