### PR TITLE
Fix to no formatting with delimiter columns named id or starts with id

### PR DESCRIPTION
**Pull request by bernardolm**
This helps when you works with a legacy databases

### CODE REVIEW

**Comment by ankane** [comment]
Thanks @bernardolm. No need to check if `key == "id"` as both start_with and end_with cover that case.

**Comment by bernardolm** [comment]
It's true, @ankane. Fixed.

**Comment by renatoelias** [comment]
👍

**Comment by ankane** [comment]
Looks good, thanks @bernardolm 👍

**Comment by bernardolm** [comment]
;D

**Pull request merged**
