### PR TITLE
Allow custom user class name

### PR DESCRIPTION
**Pull request by pjb3**
Resolves issue #4

### CODE REVIEW

**Comment by ankane** [comment]
Hey Paul, thanks for the pull request?  How about:

```ruby
Blazer.user_class_name = 'Admin'
```

to keep it consistent with the other customizations?

**Comment by pjb3** [comment]
@ankane I wanted to do that too initially but I don't think that works because you have to reference the value when you define the associations and you won't have a chance to set that value in an initializer before the models in blazer are loaded.

**Comment by paultyng** [comment]
Spree does it via an initializer and referencing the variable in its associations, so I think that works.

`Spree::Order` model: https://github.com/spree/spree/blob/master/core/app/models/spree/order.rb#L38

**Comment by ankane** [comment]
@pjb3 does #6 work for you?

**Comment by pjb3** [comment]
@ankane Yes, @paultyng's solution works fine, I didn't realize the Rails models get loaded after the initializers run

**Comment by ankane** [comment]
Thanks @pjb3, just merged #6.

**Pull request closed without merging**
